### ISSUE TITLE
Nav tabs style changes

### ISSUE THREAD

**Issue by mikemcbride** [mmcbride1007/hyperterm-electron-theme#5]
With v0.8.1 (based on forking and cloning Hyperterm), the nav tabs styles changed slightly. Here's the difference:
- pre-0.8.1: `.tab_first` gets margin-left of 76px to account for the macOS close/maximize icons. So setting the bg color on the `ul.tabs_list` is perfectly acceptable. Background color works as expected.
- 0.8.1: `ul.tabs_list` gets the left margin of 76px, so the icons have a different bg color than the tabs background.

The fix is easy enough:

``` css
.tabs_list {
    margin-left: 0; /* override the 76px left margin added to the tabs list */
    padding-left: 82px; /* 76px to offset the removed margin, plus our original .5em (6px) padding */
}
```
